<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add day care');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/day_care.php';
    $dbh_day_care = new day_care;

    $object_name = 'dbh_day_care';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_day_care.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');
		
		$srr_form_data['time_in']= date('Y-m-d_h-ia');
		
        $message .= $dbh_day_care->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_day_care->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_day_care->add($arr_form_data);
            

            redirect("listview_day_care.php?$query_string");
        }
    }
}
require 'subclasses/day_care_html.php';
$html = new day_care_html;
$html->draw_header('Add Day Care', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_controls('add');

$html->draw_footer();