<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete official');

if(isset($_GET['official_id']))
{
    $official_id = urldecode($_GET['official_id']);
    require_once 'form_data_official.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_official.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/official.php';
        $dbh_official = new official;

        $object_name = 'dbh_official';
        require 'components/create_form_data.php';

        $dbh_official->delete($arr_form_data);


        redirect("listview_official.php?$query_string");
    }
}
require 'subclasses/official_html.php';
$html = new official_html;
$html->draw_header('Delete Official', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('official_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();