<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete lending items');

if(isset($_GET['lending_items_id']))
{
    $lending_items_id = urldecode($_GET['lending_items_id']);
    require_once 'form_data_lending_items.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_lending_items.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/lending_items.php';
        $dbh_lending_items = new lending_items;

        $object_name = 'dbh_lending_items';
        require 'components/create_form_data.php';

        $dbh_lending_items->delete($arr_form_data);


        redirect("listview_lending_items.php?$query_string");
    }
}
require 'subclasses/lending_items_html.php';
$html = new lending_items_html;
$html->draw_header('Delete Lending Items', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('lending_items_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();