<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit bulletin');

if(isset($_GET['bulletin_id']))
{
    $bulletin_id = urldecode($_GET['bulletin_id']);
    require 'form_data_bulletin.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/bulletin.php';
    $dbh_bulletin = new bulletin;

    $object_name = 'dbh_bulletin';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_bulletin.php?$query_string");
    }

    $file_upload_control_name = 'file_document';
    require 'components/upload_generic.php';

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_bulletin->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_bulletin->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_bulletin->edit($arr_form_data);


            redirect("listview_bulletin.php?$query_string");
        }
    }
}
require 'subclasses/bulletin_html.php';
$html = new bulletin_html;
$html->draw_header('Edit Bulletin', $message, $message_type, TRUE, TRUE);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('bulletin_id');

$html->draw_controls('edit');

$html->draw_footer();