<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete validate');

if(isset($_GET['validate_id']))
{
    $validate_id = urldecode($_GET['validate_id']);
    require_once 'form_data_validate.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_validate.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/validate.php';
        $dbh_validate = new validate;

        $object_name = 'dbh_validate';
        require 'components/create_form_data.php';

        $dbh_validate->delete($arr_form_data);


        redirect("listview_validate.php?$query_string");
    }
}
require 'subclasses/validate_html.php';
$html = new validate_html;
$html->draw_header('Delete Validate', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('validate_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();