<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit poa&poi');

if(isset($_GET['poa_poi_id']))
{
    $poa_poi_id = urldecode($_GET['poa_poi_id']);
    require 'form_data_poa&poi.php';
    $orig_poa_poi_id = $poa_poi_id;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/poa&poi.php';
    $dbh_poa&poi = new poa&poi;

    $object_name = 'dbh_poa&poi';
    require 'components/create_form_data.php';
    $arr_form_data['orig_poa_poi_id'] = $_POST['orig_poa_poi_id'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_poa&poi.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_poa&poi->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_poa&poi->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_poa&poi->edit($arr_form_data);


            redirect("listview_poa&poi.php?$query_string");
        }
    }
}
require 'subclasses/poa&poi_html.php';
$html = new poa&poi_html;
$html->draw_header('Edit Poa&poi', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_poa_poi_id');
$html->draw_controls('edit');

$html->draw_footer();