<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add sub doc');

require 'components/get_listview_referrer.php';
if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/sub_doc.php';
    $dbh_sub_doc = new sub_doc;

    $object_name = 'dbh_sub_doc';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_sub_doc.php?$query_string");
    }

    $file_upload_control_name = 'requirement_doc';
    require 'components/upload_generic.php';

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_sub_doc->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_sub_doc->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_sub_doc->add($arr_form_data);
            

            redirect("listview_sub_doc.php?$query_string");
        }
    }
		if ($arr_form_data['document_id'] != "")
	{
		$chosen_document = $arr_form_data['document_id'];
	}


}
require 'subclasses/sub_doc_html.php';
$html = new sub_doc_html;
$html->draw_header('Add Submitted Document', $message, $message_type, TRUE, TRUE);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
require 'components/set_document_requirement.php';
$html->draw_controls('add');

$html->draw_footer();