<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete sub doc');

if(isset($_GET['sub_doc_id']))
{
    $sub_doc_id = urldecode($_GET['sub_doc_id']);
    require_once 'form_data_sub_doc.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_sub_doc.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/sub_doc.php';
        $dbh_sub_doc = new sub_doc;

        $object_name = 'dbh_sub_doc';
        require 'components/create_form_data.php';

        $dbh_sub_doc->delete($arr_form_data);


        redirect("listview_sub_doc.php?$query_string");
    }
}
require 'subclasses/sub_doc_html.php';
$html = new sub_doc_html;
$html->draw_header('Delete Submitted Document', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('sub_doc_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();