<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit sub doc');

if(isset($_GET['sub_doc_id']))
{
    $sub_doc_id = urldecode($_GET['sub_doc_id']);
    require 'form_data_sub_doc.php';
    $orig_sub_doc_id = $sub_doc_id;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/sub_doc.php';
    $dbh_sub_doc = new sub_doc;

    $object_name = 'dbh_sub_doc';
    require 'components/create_form_data.php';
    $arr_form_data['orig_sub_doc_id'] = $_POST['orig_sub_doc_id'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_sub_doc.php?$query_string");
    }

    $file_upload_control_name = 'requirement_doc';
    require 'components/upload_generic.php';

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_sub_doc->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_sub_doc->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_sub_doc->edit($arr_form_data);


            redirect("listview_sub_doc.php?$query_string");
        }
    }
}
require 'subclasses/sub_doc_html.php';
$html = new sub_doc_html;
$html->draw_header('Edit Submitted Document', $message, $message_type, TRUE, TRUE);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_sub_doc_id');
$html->draw_controls('edit');

$html->draw_footer();