<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View sub doc');

$page_title       = 'ListView: Sub Doc';
$db_subclass      = 'sub_doc';
$html_subclass    = 'sub_doc_html';
$arr_pkey_name    = array('sub_doc_id');
$results_per_page = LISTVIEW_RESULTS_PER_PAGE;

//user links / passport tags
$add_link         = 'Add sub doc';
$edit_link        = 'Edit sub doc';
$delete_link      = 'Delete sub doc';
$view_link        = 'View sub doc';

//pages - set to empty if you don't want to include them in the listview
$add_page         = 'add_sub_doc.php';
$edit_page        = 'edit_sub_doc.php';
$delete_page      = 'delete_sub_doc.php';
$view_page        = 'detailview_sub_doc.php';
$csv_page         = 'csv_sub_doc.php';
$report_page      = 'reporter_sub_doc.php';

//Extra entries under operations column (name of include file, not html code)
$operations_extra = '';

//Formatting and alignment options for data columns
$arr_formatting   = array(1=>'display_citizen_name');
$arr_alignment    = array();

//For custom join & select clause, you need to set the following variables so that the default
//listview components do not rely on DD data
$join_clause       = '';
$where_clause      = "";
$lst_fields        = '';
$arr_fields        = '';
$arr_field_labels  = '';
$lst_filter_fields = '';
$arr_filter_field_labels = '';
$arr_subtext_separators  = '';

//ORDER BY clause to use before a user clicks an ascending/descending column arrow.
$default_sort_order = '';

//Uncomment $print_settings and enable DEBUG_MODE to show the values of the settings for custom join & select
//$print_settings=TRUE;

function display_citizen_name($citizen_id)
{
		$dbh_citizen = cobalt_load_class('citizen');
		$dbh_citizen->set_fields('first_name,middle_name,last_name');
		$dbh_citizen->set_where("citizen_id='$citizen_id'");
		$dbh_citizen->exec_fetch('single');
	//	debug($dbh_citizen->dump);
		$citizen_name = '';
		if(empty($dbh_citizen->dump))
		{
			//skip
		}
		else
		{
			$first_name = $dbh_citizen->dump['first_name'];
			$middle_name = $dbh_citizen->dump['middle_name'];
			$last_name = $dbh_citizen->dump['last_name'];
			$citizen_name = $first_name . ' ' . $middle_name . ' ' . $last_name . ' ';
		}
		
		return $citizen_name;
}
require 'components/listview_proc_head.php';
require 'components/listview_proc_html.php';
require 'components/listview_proc_query.php';
require 'components/listview_body_head.php';
require 'components/listview_body_data.php';
require 'components/listview_body_end.php';