<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete barangay');

if(isset($_GET['barangay_id']))
{
    $barangay_id = urldecode($_GET['barangay_id']);
    require_once 'form_data_barangay.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_barangay.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/barangay.php';
        $dbh_barangay = new barangay;

        $object_name = 'dbh_barangay';
        require 'components/create_form_data.php';

        $dbh_barangay->delete($arr_form_data);


        redirect("listview_barangay.php?$query_string");
    }
}
require 'subclasses/barangay_html.php';
$html = new barangay_html;
$html->draw_header('Delete Barangay', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('barangay_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();