<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete zone');

if(isset($_GET['zone_id']))
{
    $zone_id = urldecode($_GET['zone_id']);
    require_once 'form_data_zone.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_zone.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/zone.php';
        $dbh_zone = new zone;

        $object_name = 'dbh_zone';
        require 'components/create_form_data.php';

        $dbh_zone->delete($arr_form_data);


        redirect("listview_zone.php?$query_string");
    }
}
require 'subclasses/zone_html.php';
$html = new zone_html;
$html->draw_header('Delete Zone', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('zone_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();