<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete poa&poi');

if(isset($_GET['poa_poi_id']))
{
    $poa_poi_id = urldecode($_GET['poa_poi_id']);
    require_once 'form_data_poa&poi.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_poa&poi.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/poa&poi.php';
        $dbh_poa&poi = new poa&poi;

        $object_name = 'dbh_poa&poi';
        require 'components/create_form_data.php';

        $dbh_poa&poi->delete($arr_form_data);


        redirect("listview_poa&poi.php?$query_string");
    }
}
require 'subclasses/poa&poi_html.php';
$html = new poa&poi_html;
$html->draw_header('Delete Poa&poi', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('poa_poi_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();