<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add request');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/request.php';
    $dbh_request = new request;

    $object_name = 'dbh_request';
   require 'components/create_form_data_with_upload.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_request.php?$query_string");
    }
	$file_upload_control_name="cf_request_has_requirement_requirement_document";
	$mf_upload_counter_name="request_has_requirement_count";
	require 'components/upload_generic_mf.php';
	

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_request->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_request->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_request->add($arr_form_data);
            $request_id = $dbh_request->auto_id;
            require_once 'subclasses/request_has_requirement.php';
            $dbh_request = new request_has_requirement;
            for($a=0; $a<$request_has_requirement_count;$a++)
            {
                $cf_request_has_requirement_date_submitted[$a] = $cf_request_has_requirement_date_submitted_year[$a] . '-' . $cf_request_has_requirement_date_submitted_month[$a] . '-' . $cf_request_has_requirement_date_submitted_day[$a];
               
                $param = array(
                               'date_submitted'=>$cf_request_has_requirement_date_submitted[$a],
                               'requirement_document'=>$cf_request_has_requirement_requirement_document[$a],
                               'request_id'=>$request_id,
                               'status'=>$cf_request_has_requirement_status[$a]
                              );
                $dbh_request->add($param);
            }


            redirect("listview_request.php?$query_string");
        }
    }
}
require 'subclasses/request_html.php';
$html = new request_html;
$html->draw_header('Add Request', $message, $message_type,TRUE,TRUE);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_controls('add');

$html->draw_footer();