<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add business permit');

require 'components/get_listview_referrer.php';
init_var($chosen_capital_investment);

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
	
    require 'components/query_string_standard.php';
    require 'subclasses/business_permit.php';
    $dbh_business_permit = new business_permit;

    $object_name = 'dbh_business_permit';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_business_permit.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');
		
		$dbh_business_permit->fields['fee_new']['required'] = FALSE;
		$dbh_business_permit->fields['fee_renew']['required'] = FALSE;
		
        $message .= $dbh_business_permit->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_business_permit->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_business_permit->add($arr_form_data);
            

            redirect("listview_business_permit.php?$query_string");
        }
    }
	if ($arr_form_data['region'] != "")
	{
		$chosen_region = $arr_form_data['region'];
	}
	
	if ($arr_form_data['province'] != "")
	{
		$chosen_province = $arr_form_data['province'];
	}
	if ($arr_form_data['city'] != "")
	{
		$chosen_city = $arr_form_data['city'];
	}
	if ($arr_form_data['barangay'] != "")
	{
		$chosen_barangay = $arr_form_data['barangay'];
	}
	if ($arr_form_data['capital_investment'] != "")
	{
		$chosen_capital_investment = $arr_form_data['capital_investment'];
		
	}
	if ($arr_form_data['type'] != "")
	{
		$chosen_type = $arr_form_data['type'];
		
	}
}
require 'subclasses/business_permit_html.php';
$html = new business_permit_html;
$html->draw_header('Add Business Permit', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
require 'components/set_region_province_city.php';
require 'components/set_business_permit.php';


$html->draw_controls('add');

$html->draw_footer();