<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete business permit fee');

if(isset($_GET['business_permit_fee_id']))
{
    $business_permit_fee_id = urldecode($_GET['business_permit_fee_id']);
    require_once 'form_data_business_permit_fee.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_business_permit_fee.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/business_permit_fee.php';
        $dbh_business_permit_fee = new business_permit_fee;

        $object_name = 'dbh_business_permit_fee';
        require 'components/create_form_data.php';

        $dbh_business_permit_fee->delete($arr_form_data);


        redirect("listview_business_permit_fee.php?$query_string");
    }
}
require 'subclasses/business_permit_fee_html.php';
$html = new business_permit_fee_html;
$html->draw_header('Delete Business Permit Fee', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('business_permit_fee_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();