<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete barangay clearance');

if(isset($_GET['barangay_clearance_id']))
{
    $barangay_clearance_id = urldecode($_GET['barangay_clearance_id']);
    require_once 'form_data_barangay_clearance.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_barangay_clearance.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/barangay_clearance.php';
        $dbh_barangay_clearance = new barangay_clearance;

        $object_name = 'dbh_barangay_clearance';
        require 'components/create_form_data.php';

        $dbh_barangay_clearance->delete($arr_form_data);


        redirect("listview_barangay_clearance.php?$query_string");
    }
}
require 'subclasses/barangay_clearance_html.php';
$html = new barangay_clearance_html;
$html->draw_header('Delete Barangay Clearance', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('barangay_clearance_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();