<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit business permit');

if(isset($_GET['business_permit_id']))
{
    $business_permit_id = urldecode($_GET['business_permit_id']);
    require 'form_data_business_permit.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/business_permit.php';
    $dbh_business_permit = new business_permit;

    $object_name = 'dbh_business_permit';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_business_permit.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_business_permit->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_business_permit->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_business_permit->edit($arr_form_data);


            redirect("listview_business_permit.php?$query_string");
        }
    }
}
require 'subclasses/business_permit_html.php';
$html = new business_permit_html;
$html->draw_header('Edit Business Permit', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('business_permit_id');

$html->draw_controls('edit');

$html->draw_footer();